/**
 * Contains the jokes and punchlines.
 *
 * !!! IMPORTANT !!!
 * The order of the fields must match the order of the joke
 * sequence!
 */


#define NUMBER_OF_FLASH_CARDS  (40)
#define FIRST_CARD (40)

// Enum for the cards
enum card_t {
  one = 0,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven,
  twelve,
  thirteen,
  fourteen,
  fifteen,
  sixteen,
  seventeen,
  eighteen,
  nineteen,
  twenty,
  twentyone,
  twentytwo,
  twentythree,
  twentyfour,
  twentyfive,
  twentysix,
  twentyseven,
  twentyeight,
  twentynine,
  thirty,
  thirtyone,
  thirtytwo,
  thirtythree,
  thirtyfour,
  thirtyfive,
  thirtysix,
  thirtyseven,
  thirtyeight,
  thirtynine,
  forty,
};

// Card Front - Line 1
char const * const aa_front_line_one[] = {
  "Cash.",
  "Doris.",
  "Honey bee.",
  "Cows go. ",
  "Oink oink. ",
  "To.",
  "The watch.",
  "Boo.",
  "Yacht! ",
  "Xavier.",
  "Ice cream! ",
  "Sadie! ",
  "Spell.",
  "Mikey! ",
  "Thermos.",
  "Hawaii. ",
  "Adore.",
  "Madam!",
  "A little old lady.",
  "Voodoo. ",
  "Stopwatch!",
  "Water.",
  "Lettuce!",
  "Baby owl.",
  "Alpaca.",
  "Anna.",
  "Canoe.",
  "Orange.",
  "Arfur.",
  "Roach.",
  "Dwayne.",
  "Two knee.",
  "Otto.",
  "King Tut.",
  "Police.",
  "A herd.",
  "Aida.",
  "Henrietta.",
  "Needle.",
  "Claire.",
  "",
};

// Card Front - Line 2
char const * const aa_front_line_two[] = {
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who?  ---->",
  "who's there?   ",
};

// Card Back - Line 1
char const * const aa_back_line_one[] = {
  "No thanks, but I would like a peanut instead!",
  "Doris locked, that's why I'm knocking!",
  "Honey bee a dear and get me a soda!",
  "No, cows go moo!",
  "Make up your mind, are you a pig or an owl?!",
  "To whom.",
  "Gesundheit!",
  "Aww, don't cry, it was only a joke!",
  "Yacht a know me by now!",
  "Xavier breath and open that door!",
  "Ice cream if you don't let me in!",
  "Sadie air is hot out here!",
  "OK, W_H_O.",
  "Mikey doesn't fit in the keyhole!",
  "Thermos be a better knock-knock joke than this.",
  "I'm fine. Hawaii you?",
  "Adore stands between us, open up!",
  "Madam foot got caught in the door!",
  "I didn't know you could yodel.",
  "Voodoo you think you are?",
  "Stopwatch you're doing and open this door!",
  "Water you doing? Open the door!",
  "Lettuce in! It's cold out here!",
  "Baby owl see you as soon as you open up!",
  "Alpaca the trunk, you pack the suitcase.",
  "Anna one, anna two . . .",
  "Canoe help me with my homework?",
  "Orange you going to let me in?",
  "Arfur got!",
  "Roach you a letter, did you get it?",
  "Dwayne the bathtub, I'm dwowning!",
  "Two-knee fish!",
  "Otto know. I’ve got amnesia.",
  "King Tut-key fried chicken!",
  "Police hurry up, it’s chilly outside!",
  "A herd you were home, so I came over!",
  "Aida sandwich for lunch today.",
  "Henrietta worm that was in his apple.",
  "Needle little money for the movies.",
  "Claire the way, I’m coming through!",
  "knock with your hand and ask 'who's there?'! KNOCK! KNOCK!"
};
